config/routes.rb
Rails.application.routes.draw do
  resources :maps
  resources :users

  root 'maps#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/map.rb
class Map < ApplicationRecord
  belongs_to :user
  has_many :places
  validates :title, :description, presence: true
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :map
  geocoded_by :full_street_address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates

  def address
    [self.full_street_address, self.city, self.state].compact.join(', ')
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :maps
  validates :first_name, :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
    @maps = Map.all.order('created_at DESC')
  end

  def new
    @map = Map.new
  end

  def create
    @map = Map.new(map_params)
    if @map.save
      redirect_to @map
    else
      render 'new'
    end
  end

  def show
    @map = Map.find(params[:id])
    @places = @map.places
  end

  def edit
    @map = Map.find(params[:id])
  end

  def update
    @map = Map.find(params[:id])
    if @map.update(params[:map].permit(:title, :description, :xuser_id))
      redirect_to @map
    else
      render 'edit'
    end
  end

  def destroy
    @map = Map.find(params[:id])
    @map.destroy

    redirect_to root_path
  end

  private
    def map_params
      params.require(:map).permit(:title, :description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find(email: params[:email])
    if @user && @user.authenicate(params[:password])
      session[:user_id] = @user.user_id
      redirect_to root_path
    else
      @message = "Either your email or password is incorrect."
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(session[:user_id])
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Legend</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <div class='nav'>
          <%= link_to 'home', root_path %> | login | signup
        </div>
        <div id="sidebar">
          <ul>
            <li class="category">Maps</li>
            <li><%= link_to "home", root_path %></li>
            <li>about</li>
            <li></li>
          </ul>
          <ul>
            <li class="category">Contact</li>
            <li><a href="https://github.com/kthong3">github</a></li>
          </ul>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/maps/_form.html.erb
<%= form_for @map do |f| %>
  <% if @map.errors.any? %>
    <div id="errors">
      <h2><%= pluralize(@map.errors.count, "error") %> prevented this map from saving </h2>
      <ul>
        <%= @map.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul >
    </div>
  <% end %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/maps/_map.html.erb
<div class="map-wrapper">
  <ul>
    <p>
      Title: <%= link_to map.title, map %><br>
      Description: <%= map.description %>
      <br>
      Created: <%= map.created_at.strftime("%B, %d, %Y") %>
    </p>
  </ul>
</div>

app/views/maps/index.html.erb
<h1>Maps</h1>
<div class="container">
  <%= render @maps || "There are no maps yet!" %>
</div>

app/views/maps/new.html.erb
<div id="content_wrapper">
  <h1>New Map</h1>

  <%= render 'form' %>
</div>

app/views/maps/show.html.erb
<div class="map-content">
  <h1 class="title">
    <%= @map.title %>
  </h1>
  <% @places.each do |place| %>
    <iframe
      width="300" height="300" frameborder="0"
      style="border:0" src="//www.google.com/maps/embed/v1/place?q=<%= place.address %>
      &zoom=17
      &key=<%= ENV['API_KEY'] %>" allowfullscreen>
    </iframe>
  <% end %>

  <p class="date">
    Submitted <%= time_ago_in_words(@map.created_at) %> | <%= link_to 'edit', edit_map_path %> | <%= link_to 'delete', map_path(@map), method: :delete, data: { confirm: "Are you sure you want to delete this map?"} %>
  </p>

  <p class="description">
    <%= @map.description %>
  </p>
</div>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit "sign up" %>
<% end %>